// =══════════════════════════════════════════
// STANDARD CARD DEFINITION FORMAT
// Use: "French Phrase | English Translation | category_key"
// =══════════════════════════════════════════

const FLASHCARD_DATA = [
  // GREETINGS & PHRASES
  "Bonjour|Hello / Good morning|greetings",
  "Bonsoir|Good evening|greetings",
  "Bonne nuit|Good night|greetings",
  "Salut|Hi / Bye (informal)|greetings",
  "Au revoir|Goodbye|greetings",
  "À bientôt|See you soon|greetings",
  "À demain|See you tomorrow|greetings",
  "À tout à l'heure|See you later (same day)|greetings",
  "S'il vous plaît|Please (formal)|greetings",
  "S'il te plaît|Please (informal)|greetings",
  "Merci|Thank you|greetings",
  "Merci beaucoup|Thank you very much|greetings",
  "De rien|You're welcome|greetings",
  "Avec plaisir|With pleasure|greetings",
  "Excusez-moi|Excuse me (formal)|greetings",
  "Pardon|Sorry / Pardon|greetings",
  "Je suis désolé / désolée|I'm sorry|greetings",
  "Ce n'est pas grave|It doesn't matter|greetings",
  "Je ne comprends pas|I don't understand|greetings",
  "Pouvez-vous répéter ?|Can you repeat?|greetings",
  "Plus lentement, s'il vous plaît|More slowly, please|greetings",
  "Vous parlez anglais ?|Do you speak English?|greetings",
  "Comment vous appelez-vous ?|What is your name? (formal)|greetings",
  "Comment tu t'appelles ?|What is your name? (informal)|greetings",
  "Je m'appelle…|My name is…|greetings",
  "Ça va ?|How are you? (informal)|greetings",
  "Ça va bien, merci|I'm fine, thank you|greetings",
  "Comme ci comme ça|So-so|greetings",
  "Pas mal|Not bad|greetings",
  "Enchanté / Enchantée|Nice to meet you|greetings",
  "Bienvenue|Welcome|greetings",
  "Bonne chance|Good luck|greetings",
  "Bon appétit|Enjoy your meal|greetings",
  "Joyeux anniversaire|Happy birthday|greetings",
  "Félicitations|Congratulations|greetings",

  // NUMBERS & TIME
  "zéro|0|numbers",
  "un, deux, trois|1, 2, 3|numbers",
  "quatre, cinq, six|4, 5, 6|numbers",
  "sept, huit, neuf|7, 8, 9|numbers",
  "dix, onze, douze|10, 11, 12|numbers",
  "treize, quatorze, quinze|13, 14, 15|numbers",
  "seize, dix-sept, dix-huit|16, 17, 18|numbers",
  "dix-neuf, vingt|19, 20|numbers",
  "vingt et un|21|numbers",
  "trente|30|numbers",
  "quarante|40|numbers",
  "cinquante|50|numbers",
  "soixante|60|numbers",
  "soixante-dix|70|numbers",
  "soixante et onze|71|numbers",
  "quatre-vingts|80|numbers",
  "quatre-vingt-un|81|numbers",
  "quatre-vingt-dix|90|numbers",
  "cent|100|numbers",
  "mille|1000|numbers",
  "premier / première|first|numbers",
  "deuxième|second|numbers",
  "troisième|third|numbers",
  "lundi|Monday|numbers",
  "mardi|Tuesday|numbers",
  "mercredi|Wednesday|numbers",
  "jeudi|Thursday|numbers",
  "vendredi|Friday|numbers",
  "samedi|Saturday|numbers",
  "dimanche|Sunday|numbers",
  "janvier|January|numbers",
  "février|February|numbers",
  "mars|March|numbers",
  "avril|April|numbers",
  "mai|May|numbers",
  "juin|June|numbers",
  "juillet|July|numbers",
  "août|August|numbers",
  "septembre|September|numbers",
  "octobre|October|numbers",
  "novembre|November|numbers",
  "décembre|December|numbers",
  "aujourd'hui|today|numbers",
  "demain|tomorrow|numbers",
  "hier|yesterday|numbers",
  "avant-hier|the day before yesterday|numbers",
  "après-demain|the day after tomorrow|numbers",
  "le matin|the morning|numbers",
  "l'après-midi|the afternoon|numbers",
  "le soir|the evening|numbers",
  "la nuit|the night|numbers",
  "Quelle heure est-il ?|What time is it?|numbers",
  "Il est… heures|It is… o'clock|numbers",
  "Il est midi|It is midday|numbers",
  "Il est minuit|It is midnight|numbers",
  "et quart|quarter past|numbers",
  "et demie|half past|numbers",
  "moins le quart|quarter to|numbers",

  // FAMILY & PEOPLE
  "la mère|mother|family",
  "le père|father|family",
  "la sœur|sister|family",
  "le frère|brother|family",
  "la grand-mère|grandmother|family",
  "le grand-père|grandfather|family",
  "la petite-fille|granddaughter|family",
  "le petit-fils|grandson|family",
  "la tante|aunt|family",
  "l'oncle|uncle|family",
  "la cousine|cousin (f)|family",
  "le cousin|cousin (m)|family",
  "la fille|daughter / girl|family",
  "le fils|son|family",
  "l'enfant|child|family",
  "le bébé|baby|family",
  "le mari|husband|family",
  "la femme|wife / woman|family",
  "le petit ami|boyfriend|family",
  "la petite amie|girlfriend|family",
  "l'ami / l'amie|friend (m/f)|family",
  "le collègue|colleague|family",
  "le professeur|teacher|family",
  "le médecin|doctor|family",
  "l'homme|man|family",
  "la personne|person|family",
  "les gens|people|family",
  "jeune|young|family",
  "âgé / âgée|elderly|family",
  "célibataire|single|family",
  "marié / mariée|married|family",

  // FOOD & DRINK
  "le pain|bread|food",
  "la baguette|baguette|food",
  "le croissant|croissant|food",
  "le fromage|cheese|food",
  "le beurre|butter|food",
  "la viande|meat|food",
  "le poulet|chicken|food",
  "le bœuf|beef|food",
  "le porc|pork|food",
  "le poisson|fish|food",
  "les crevettes|prawns / shrimp|food",
  "les légumes|vegetables|food",
  "la pomme de terre|potato|food",
  "la tomate|tomato|food",
  "la carotte|carrot|food",
  "l'oignon|onion|food",
  "les fruits|fruit|food",
  "la pomme|apple|food",
  "la banane|banana|food",
  "l'orange|orange|food",
  "la fraise|strawberry|food",
  "la salade|salad|food",
  "le riz|rice|food",
  "les pâtes|pasta|food",
  "la soupe|soup|food",
  "l'œuf|egg|food",
  "le sucre|sugar|food",
  "le sel|salt|food",
  "l'huile|oil|food",
  "l'eau|water|food",
  "l'eau gazeuse|sparkling water|food",
  "le café|coffee|food",
  "le thé|tea|food",
  "le jus d'orange|orange juice|food",
  "le vin|wine|food",
  "la bière|beer|food",
  "le lait|milk|food",
  "le petit-déjeuner|breakfast|food",
  "le déjeuner|lunch|food",
  "le dîner|dinner|food",
  "J'ai faim|I'm hungry|food",
  "J'ai soif|I'm thirsty|food",
  "C'est délicieux|It's delicious|food",
  "L'addition, s'il vous plaît|The bill, please|food",

  // PLACES & DIRECTIONS
  "la ville|city / town|places",
  "le village|village|places",
  "la campagne|countryside|places",
  "la rue|street|places",
  "l'avenue|avenue|places",
  "la place|square / plaza|places",
  "la maison|house|places",
  "l'appartement|apartment|places",
  "l'immeuble|building|places",
  "l'école|school|places",
  "le collège|middle school|places",
  "le lycée|high school|places",
  "l'université|university|places",
  "le bureau|office|places",
  "le magasin|shop|places",
  "le supermarché|supermarket|places",
  "le marché|market|places",
  "la pharmacie|pharmacy|places",
  "l'hôpital|hospital|places",
  "la banque|bank|places",
  "la poste|post office|places",
  "la bibliothèque|library|places",
  "l'église|church|places",
  "le musée|museum|places",
  "le parc|park|places",
  "la gare|train station|places",
  "l'aéroport|airport|places",
  "le métro|metro / underground|places",
  "le restaurant|restaurant|places",
  "le café|café|places",
  "l'hôtel|hotel|places",
  "à gauche|to the left|places",
  "à droite|to the right|places",
  "tout droit|straight ahead|places",
  "près de|near / close to|places",
  "loin de|far from|places",
  "en face de|opposite|places",
  "au coin de|on the corner of|places",
  "au bout de|at the end of|places",
  "au premier étage|on the first floor|places",
  "au rez-de-chaussée|on the ground floor|places",

  // COLOURS & ADJECTIVES
  "rouge|red|adjectives",
  "bleu / bleue|blue|adjectives",
  "vert / verte|green|adjectives",
  "jaune|yellow|adjectives",
  "noir / noire|black|adjectives",
  "blanc / blanche|white|adjectives",
  "rose|pink|adjectives",
  "orange|orange (invariable)|adjectives",
  "gris / grise|grey|adjectives",
  "violet / violette|purple|adjectives",
  "marron|brown (invariable)|adjectives",
  "beige|beige (invariable)|adjectives",
  "grand / grande|big / tall|adjectives",
  "petit / petite|small|adjectives",
  "gros / grosse|fat / large|adjectives",
  "mince|slim|adjectives",
  "long / longue|long|adjectives",
  "court / courte|short (length)|adjectives",
  "haut / haute|high / tall|adjectives",
  "bas / basse|low|adjectives",
  "bon / bonne|good|adjectives",
  "mauvais / mauvaise|bad|adjectives",
  "beau / belle|beautiful|adjectives",
  "joli / jolie|pretty|adjectives",
  "laid / laide|ugly|adjectives",
  "nouveau / nouvelle|new|adjectives",
  "vieux / vieille|old|adjectives",
  "jeune|young|adjectives",
  "chaud / chaude|hot|adjectives",
  "froid / froide|cold|adjectives",
  "rapide|fast (invariable)|adjectives",
  "lent / lente|slow|adjectives",
  "facile|easy (invariable)|adjectives",
  "difficile|hard (invariable)|adjectives",
  "cher / chère|expensive|adjectives",
  "gratuit / gratuite|free|adjectives",
  "sympa|nice (invariable)|adjectives",
  "content / contente|happy|adjectives",
  "triste|sad (invariable)|adjectives",
  "fatigué / fatiguée|tired|adjectives",
  "occupé / occupée|busy|adjectives",
  "fort / forte|strong|adjectives",
  "faible|weak (invariable)|adjectives",
  "plein / pleine|full|adjectives",
  "vide|empty (invariable)|adjectives",

  // CORE VERBS
  "être|to be|verbs",
  "avoir|to have|verbs",
  "aller|to go|verbs",
  "faire|to do / make|verbs",
  "vouloir|to want|verbs",
  "pouvoir|to be able to|verbs",
  "devoir|to have to|verbs",
  "savoir|to know (a fact)|verbs",
  "connaître|to know (a person/place)|verbs",
  "voir|to see|verbs",
  "dire|to say|verbs",
  "mettre|to put|verbs",
  "prendre|to take|verbs",
  "venir|to come|verbs",
  "partir|to leave|verbs",
  "sortir|to go out|verbs",
  "dormir|to sleep|verbs",
  "finir|to finish|verbs",
  "choisir|to choose|verbs",
  "parler|to speak|verbs",
  "manger|to eat|verbs",
  "habiter|to live (somewhere)|verbs",
  "travailler|to work|verbs",
  "aimer|to like / love|verbs",
  "écouter|to listen|verbs",
  "regarder|to watch|verbs",
  "chercher|to look for|verbs",
  "acheter|to buy|verbs",
  "s'appeler|to be called|verbs",
  "se lever|to get up|verbs",

  // BODY
  "la tête|head|body",
  "le visage|face|body",
  "les cheveux|hair|body",
  "les yeux|eyes|body",
  "l'œil|eye|body",
  "le nez|nose|body",
  "la bouche|mouth|body",
  "l'oreille|ear|body",
  "les dents|teeth|body",
  "le cou|neck|body",
  "l'épaule|shoulder|body",
  "le bras|arm|body",
  "la main|hand|body",
  "le doigt|finger|body",
  "la jambe|leg|body",
  "le pied|foot|body",
  "le dos|back|body",
  "le ventre|stomach / belly|body",
  "le cœur|heart|body",
  "J'ai mal à la tête|I have a headache|body",
  "J'ai mal au ventre|I have a stomachache|body",
  "Je suis malade|I am sick|body",
  "Je me sens bien|I feel well|body",
  "fatigué / fatiguée|tired|body",
  "en bonne santé|in good health|body",

  // CLOTHING
  "les vêtements|clothes|clothing",
  "la chemise|shirt|clothing",
  "le t-shirt|t-shirt|clothing",
  "le pull|jumper / sweater|clothing",
  "la veste|jacket|clothing",
  "le manteau|coat|clothing",
  "le pantalon|trousers|clothing",
  "le jean|jeans|clothing",
  "la jupe|skirt|clothing",
  "la robe|dress|clothing",
  "le short|shorts|clothing",
  "les chaussures|shoes|clothing",
  "les baskets|trainers / sneakers|clothing",
  "les bottes|boots|clothing",
  "les chaussettes|socks|clothing",
  "le chapeau|hat|clothing",
  "l'écharpe|scarf|clothing",
  "les gants|gloves|clothing",
  "porter|to wear|clothing",
  "mettre|to put on|clothing",
  "Je porte…|I am wearing…|clothing",
  "Quelle taille ?|What size?|clothing",
  "grand / moyen / petit|large / medium / small|clothing",
  "ça me va|it suits me / it fits me|clothing",
  "C'est trop grand|It's too big|clothing",

  // HOME
  "la maison|house|home",
  "l'appartement|apartment|home",
  "la chambre|bedroom|home",
  "la salle de bain|bathroom|home",
  "la cuisine|kitchen|home",
  "le salon|living room|home",
  "la salle à manger|dining room|home",
  "les toilettes|toilet|home",
  "le jardin|garden|home",
  "le balcon|balcony|home",
  "la porte|door|home",
  "la fenêtre|window|home",
  "le lit|bed|home",
  "la table|table|home",
  "la chaise|chair|home",
  "le canapé|sofa|home",
  "l'armoire|wardrobe|home",
  "le réfrigérateur|fridge|home",
  "la télévision|television|home",
  "l'ordinateur|computer|home",
  "le téléphone|phone|home",
  "habiter|to live (somewhere)|home",
  "J'habite à…|I live in…|home",
  "au premier étage|on the first floor|home",
  "C'est grand / petit|It's big / small|home",

  // TRANSPORT
  "la voiture|car|transport",
  "le bus|bus|transport",
  "le train|train|transport",
  "le métro|metro / underground|transport",
  "le vélo|bicycle|transport",
  "la moto|motorbike|transport",
  "l'avion|plane|transport",
  "le taxi|taxi|transport",
  "le bateau|boat|transport",
  "à pied|on foot|transport",
  "prendre le bus|to take the bus|transport",
  "conduire|to drive|transport",
  "le billet|ticket|transport",
  "l'arrêt de bus|bus stop|transport",
  "la gare|train station|transport",
  "l'aéroport|airport|transport",
  "partir|to leave / depart|transport",
  "arriver|to arrive|transport",
  "À quelle heure part le train ?|What time does the train leave?|transport",
  "C'est loin ?|Is it far?|transport",

  // SCHOOL & WORK
  "l'école|school|school",
  "la classe|classroom|school",
  "le cours|lesson / class|school",
  "le professeur|teacher|school",
  "l'élève|pupil|school",
  "l'étudiant / l'étudiante|student (m/f)|school",
  "le livre|book|school",
  "le cahier|notebook|school",
  "le stylo|pen|school",
  "le crayon|pencil|school",
  "le bureau|desk / office|school",
  "le cartable|school bag|school",
  "les devoirs|homework|school",
  "l'examen|exam|school",
  "la note|grade / mark|school",
  "travailler|to work|school",
  "étudier|to study|school",
  "apprendre|to learn|school",
  "écrire|to write|school",
  "lire|to read|school",
  "le travail|work / job|school",
  "le métier|profession|school",
  "le collègue|colleague|school",
  "Je travaille dans…|I work in…|school",
  "Qu'est-ce que vous faites ?|What do you do for work?|school",

  // WEATHER & SEASONS
  "la météo|the weather|weather",
  "le temps|the weather / time|weather",
  "le soleil|sun|weather",
  "la pluie|rain|weather",
  "le vent|wind|weather",
  "la neige|snow|weather",
  "le nuage|cloud|weather",
  "il fait chaud|it's hot|weather",
  "il fait froid|it's cold|weather",
  "il fait beau|the weather is nice|weather",
  "il pleut|it's raining|weather",
  "il neige|it's snowing|weather",
  "il y a du vent|it's windy|weather",
  "il y a du soleil|it's sunny|weather",
  "le printemps|spring|weather",
  "l'été|summer|weather",
  "l'automne|autumn|weather",
  "l'hiver|winter|weather",
  "Quel temps fait-il ?|What's the weather like?|weather",
  "Il fait combien de degrés ?|What's the temperature?|weather",

  // HOBBIES
  "les loisirs|hobbies / free time|hobbies",
  "le sport|sport|hobbies",
  "la musique|music|hobbies",
  "la lecture|reading|hobbies",
  "le cinema|cinema|hobbies",
  "la télévision|television|hobbies",
  "le jeu vidéo|video game|hobbies",
  "le dessin|drawing|hobbies",
  "la cuisine|cooking|hobbies",
  "la danse|dance|hobbies",
  "le football|football|hobbies",
  "la natation|swimming|hobbies",
  "le tennis|tennis|hobbies",
  "jouer|to play|hobbies",
  "écouter de la musique|to listen to music|hobbies",
  "regarder un film|to watch a film|hobbies",
  "lire un livre|to read a book|hobbies",
  "faire du sport|to do sport|hobbies",
  "aller au cinéma|to go to the cinema|hobbies",
  "J'aime…|I like…|hobbies",
  "Je n'aime pas…|I don't like…|hobbies",
  "J'adore…|I love…|hobbies",
  "Je préfère…|I prefer…|hobbies",
  "le week-end|the weekend|hobbies",
  "pendant mon temps libre|in my free time|hobbies",

  // SHOPPING
  "le magasin|shop|shopping",
  "le marché|market|shopping",
  "le supermarché|supermarket|shopping",
  "la boulangerie|bakery|shopping",
  "la pharmacie|pharmacy|shopping",
  "acheter|to buy|shopping",
  "vendre|to sell|shopping",
  "payer|to pay|shopping",
  "Combien ça coûte ?|How much does it cost?|shopping",
  "C'est combien ?|How much is it?|shopping",
  "C'est cher|It's expensive|shopping",
  "C'est bon marché|It's cheap|shopping",
  "la monnaie|change / coins|shopping",
  "la carte bancaire|bank card|shopping",
  "en espèces|in cash|shopping",
  "Je voudrais…|I would like…|shopping",
  "Vous avez… ?|Do you have…?|shopping",
  "Quelle taille ?|What size?|shopping",
  "Je regarde seulement|I'm just looking|shopping",
  "L'addition / la note|The bill|shopping",

  // MORE PRACTICAL A1 CONTENT
  "Comment ça va ?|How are you?|greetings",
  "Je vais bien, merci|I'm doing well, thank you|greetings",
  "Je suis fatigué / fatiguée|I'm tired|greetings",
  "Je suis prêt / prête|I'm ready|greetings",
  "Je suis en retard|I'm late|greetings",
  "Je viens de France|I come from France|greetings",
  "Je suis étudiant / étudiante|I am a student|greetings",
  "Quel âge avez-vous ?|How old are you?|greetings",
  "J'ai 20 ans|I am 20 years old|greetings",
  "Quel est votre nom ?|What is your name?|greetings",
  "Où habitez-vous ?|Where do you live?|greetings",
  "J'habite à Londres|I live in London|greetings",
  "Je peux vous aider ?|Can I help you?|greetings",
  "Bien sûr|Of course|greetings",
  "D'accord|Okay / Agreed|greetings",
  "À quelle heure ?|At what time?|numbers",
  "Il est deux heures|It is two o'clock|numbers",
  "Il est trois heures et demie|It is half past three|numbers",
  "Le matin|In the morning|numbers",
  "Le soir|In the evening|numbers",
  "la semaine|the week|numbers",
  "le mois|the month|numbers",
  "l'année|the year|numbers",
  "les parents|parents|family",
  "les grands-parents|grandparents|family",
  "le voisin / la voisine|neighbour (m/f)|family",
  "la belle-mère|mother-in-law|family",
  "le beau-père|father-in-law|family",
  "les jumeaux|twins|family",
  "avoir faim|to be hungry|food",
  "avoir soif|to be thirsty|food",
  "un café noir|a black coffee|food",
  "un thé chaud|a hot tea|food",
  "du pain grillé|toast|food",
  "de la confiture|jam|food",
  "des frites|chips / fries|food",
  "du fromage blanc|white cheese|food",
  "une salade verte|a green salad|food",
  "Je prends…|I'll have…|food",
  "Je voudrais un sandwich|I would like a sandwich|food",
  "la boulangerie|bakery|places",
  "le centre-ville|city centre|places",
  "la plage|beach|places",
  "la montagne|mountain|places",
  "la forêt|forest|places",
  "la station|station|places",
  "le quartier|neighbourhood|places",
  "Où est… ?|Where is…?|places",
  "C'est près d'ici|It's near here|places",
  "C'est loin|It's far|places",
  "très|very|adjectives",
  "un peu|a little|adjectives",
  "beaucoup|a lot|adjectives",
  "sûr / sûre|sure|adjectives",
  "important / importante|important|adjectives",
  "intéressant / intéressante|interesting|adjectives",
  "amusant / amusante|fun|adjectives",
  "calme|calm|adjectives",
  "bruyant / bruyante|noisy|adjectives",
  "propre|clean|adjectives",
  "sale|dirty|adjectives",
  "chaud / chaude|warm|adjectives",
  "frais / fraîche|fresh|adjectives",
  "comprendre|to understand|verbs",
  "attendre|to wait|verbs",
  "répondre|to answer|verbs",
  "trouver|to find|verbs",
  "donner|to give|verbs",
  "réserver|to book|verbs",
  "oublier|to forget|verbs",
  "préférer|to prefer|verbs",
  "commencer|to start|verbs",
  "continuer|to continue|verbs",
  "la santé|health|body",
  "les dents|teeth|body",
  "la gorge|throat|body",
  "les jambes|legs|body",
  "les pieds|feet|body",
  "les oreilles|ears|body",
  "Je tousse|I cough|body",
  "J'ai froid|I am cold|body",
  "J'ai chaud|I am hot|body",
  "les lunettes|glasses|clothing",
  "la ceinture|belt|clothing",
  "les sandales|sandals|clothing",
  "les chaussons|slippers|clothing",
  "le costume|suit|clothing",
  "le pyjama|pyjamas|clothing",
  "porter des lunettes|to wear glasses|clothing",
  "la cuisine|kitchen|home",
  "la salle de bain|bathroom|home",
  "le lave-vaisselle|dishwasher|home",
  "la machine à laver|washing machine|home",
  "la télévision|television|home",
  "le canapé|sofa|home",
  "la lampe|lamp|home",
  "la voiture|car|transport",
  "le vélo|bicycle|transport",
  "la station de métro|metro station|transport",
  "la ligne|line|transport",
  "le ticket|ticket|transport",
  "la carte de transport|transport card|transport",
  "Je prends le train|I take the train|transport",
  "la salle de classe|classroom|school",
  "la matière|subject|school",
  "la récréation|break|school",
  "les devoirs|homework|school",
  "une question|a question|school",
  "une réponse|an answer|school",
  "Il y a du soleil|It is sunny|weather",
  "Il y a des nuages|It is cloudy|weather",
  "Il gèle|It is freezing|weather",
  "Il fait doux|It is mild|weather",
  "Il fait frais|It is cool|weather",
  "faire du vélo|to cycle|hobbies",
  "faire du jogging|to jog|hobbies",
  "faire de la randonnée|to go hiking|hobbies",
  "faire la cuisine|to cook|hobbies",
  "aller au parc|to go to the park|hobbies",
  "regarder la télévision|to watch television|hobbies",
  "écouter de la radio|to listen to the radio|hobbies",
  "j'aime lire|I like reading|hobbies",
  "j'aime cuisiner|I like cooking|hobbies",
  "J'ai besoin de…|I need…|shopping",
  "Je cherche…|I'm looking for…|shopping",
  "Est-ce que c'est disponible ?|Is it available?|shopping",
  "Je prends ça|I'll take this|shopping",
  "C'est parfait|It's perfect|shopping"
];